import { energyHistory } from "@/data/mockData";
import { Area, AreaChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
/** Grid Atlas: energy charts expose a single operational comparison, never decorative data. */
const configuration = {
  solar: { label: "Solar generation", key: "solar", color: "#d8ff3e", companion: "forecast", companionLabel: "Solar forecast", companionColor: "#78827f" },
  demand: { label: "Facility demand", key: "demand", color: "#69c8ff", companion: "solar", companionLabel: "Solar supply", companionColor: "#d8ff3e" },
  battery: { label: "Battery power", key: "battery", color: "#c49bff", companion: undefined, companionLabel: "", companionColor: "" },
  grid: { label: "Grid consumption", key: "grid", color: "#f1bf70", companion: undefined, companionLabel: "", companionColor: "" },
} as const;
export function EnergyChart({ type }: { type: keyof typeof configuration }) { const chart = configuration[type]; return <div className="h-[220px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={energyHistory} margin={{ top: 12, right: 6, left: -24, bottom: 0 }}><defs><linearGradient id={`${type}Fill`} x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor={chart.color} stopOpacity={0.28} /><stop offset="100%" stopColor={chart.color} stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#ffffff" strokeOpacity={0.07} strokeDasharray="2 6" /><XAxis dataKey="time" axisLine={false} tickLine={false} tick={{ fill: "#78807e", fontSize: 10, fontFamily: "IBM Plex Mono" }} tickMargin={11} /><YAxis axisLine={false} tickLine={false} tick={{ fill: "#78807e", fontSize: 10, fontFamily: "IBM Plex Mono" }} /><Tooltip cursor={{ stroke: chart.color, strokeOpacity: 0.3 }} contentStyle={{ background: "#121819", border: "1px solid rgba(255,255,255,.1)", borderRadius: "10px", fontFamily: "IBM Plex Mono", fontSize: "11px" }} labelStyle={{ color: chart.color, marginBottom: 6 }} itemStyle={{ color: "#e5eae7" }} /><Legend iconType="circle" wrapperStyle={{ fontFamily: "IBM Plex Mono", fontSize: 10, paddingTop: 12 }} /><Area type="monotone" dataKey={chart.key} name={chart.label} stroke={chart.color} strokeWidth={2.2} fill={`url(#${type}Fill)`} activeDot={{ r: 4, fill: chart.color, stroke: "#101718", strokeWidth: 2 }} />{chart.companion && <Area type="monotone" dataKey={chart.companion} name={chart.companionLabel} stroke={chart.companionColor} strokeDasharray="4 5" strokeWidth={1.3} fill="transparent" />}</AreaChart></ResponsiveContainer></div>; }
